### ISSUE TITLE
version is missing from previous step

### ISSUE THREAD

**Issue by robertsonic** [r-bar/concourse-github-status#1]
Hi,

Understand you've not done a commit to this since 2020. But I'm trying to use your resource in Concourse 7.7.1 as a simple test im trying to apply a status to the branch used in the pipeline. But recieve the following error in the "in/get" script:

![image](https://user-images.githubusercontent.com/23071053/185505836-67178d11-54de-4909-b17b-1b39f28204b0.png)

Here is a truncated version of my pipeline.yml

```
resources:
  - name: gitcontents
    type: git
    icon: github
    check_every: 15s
    source:
      uri: https://((REPOSITORY.GIT))/((REPOSITORY.OWNER))/((REPOSITORY.REPO)) 
      branch: ((BRANCH))
      password: ((gittoken))
      username: "gittoken@((REPOSITORY.GIT))"
  - name: build-status
    type: github-status
    source:
      owner: ((REPOSITORY.OWNER))
      repository: ((REPOSITORY.REPO))
      access_token: ((gittoken))

resource_types:
  - name: github-status
    type: docker-image
    source:
      repository: "registry.barth.tech/library/github-status-resource" # +
      tag: latest

jobs:
  - name: test
    plan:
      - put: build-status
        params: { state: success, commit: gitcontents }
```

I'm guessing the check code in this resource is not returning a value that concourse is happy with. Help is appreciated
